### ISSUE TITLE
`<board />` center alignment bug

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/schematic-viewer#48]
File - https://github.com/tscircuit/schematic-viewer/blob/714e6a0189cd7ba887ffb20a4add964ba086417e/src/stories/bugs/bug8-autolayout.stories.tsx

`<board />` props `pcbCenterX` and `pcbCenterY` which are depreciated when replaced with `pcbX` and `pcbY` is having bug

| Current    |   |
| -------- | ------- |
| <img width="688" alt="Screenshot 2024-07-21 at 12 51 52 AM" src="https://github.com/user-attachments/assets/03529e28-c10d-43f1-8adf-db0ac68ed49c">  |  |

| After val update    |   |
| -------- | ------- |
| <img width="688" alt="Screenshot 2024-07-21 at 12 55 51 AM" src="https://github.com/user-attachments/assets/d354cf87-5b11-4704-99bb-fff270af8e81">  |  |

**Comment by seveibar** [comment]
Anything in the console?

**Comment by imrishabh18** [comment]
The props need to be updated, it seems.

<img width="630" alt="Screenshot 2024-07-21 at 6 33 25 PM" src="https://github.com/user-attachments/assets/6e2e4fec-0246-46b4-a684-d4eaadc752e3">

**Comment by seveibar** [comment]
I just patched this in the latest version of builder yesterday https://github.com/tscircuit/builder/pull/79

cc @Slaviiiii
