### ISSUE TITLE
Replace the lib/types with the circuit-json types

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/schematic-viewer#63]
We can remove the types defined in [core](https://github.com/tscircuit/schematic-viewer/blob/970303099fde5dd51db0bd4139568b1617a92272/src/lib/types/core.ts) and replace the types which are exported from `circuit-json` package.

**Comment by DhairyaMajmudar** [comment]
@imrishabh18 this seems to be a good issue to start with can you pls. assign me :)

**Comment by imrishabh18** [comment]
Great! @DhairyaMajmudar
